author: "OMikkel"

name: 'Check for console.log'

description: 'Ensure no console.log is left in the code'

inputs:
  before-sha:
    description: 'Sha of the commit before the push'
    required: true
    default: ''
  after-sha:
    description: 'Sha of the commit'
    required: true
    default: ''
  search-term:
    description: 'What to search for'
    required: true
    default: ''
outputs:
  all:
    description: 'A list of all the changed typescript/javascript files'
runs:
  using: 'node16'
  main: 'index.js'

