author: "OMikkel"

name: 'Check for console.log'

description: 'Ensure no console.log is left in the code'

inputs:
  before-sha:
    description: 'Sha of the commit before the push'
    required: true
    default: ''
  after-sha:
    description: 'Sha of the commit'
    required: true
    default: ''
  search-term:
    description: 'What to search for'
    required: true
    default: ''
  file-types:
    description: 'File types to search for'
    required: true
    default: ''
  should-fail:
    description: 'Should the action fail if the search term is found'
    required: false
    default: 'false'
outputs:
  all:
    description: 'A list of all the changed typescript/javascript files'
  occurences:
    description: 'A list of all the occurences of the search term'
runs:
  using: 'node16'
  main: 'index.js'

